env:
  browser: true
  node: true
  es6: true
extends:
  - standard
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - node
rules:
  quotes:
    - error
    - double
  semi:
    - error
    - never
  indent:
    - error
    - 4
