const constant = {
    SELECT_VIEW: "SELECT_VIEW",
    SELECT_TAB: "SELECT_TAB",
    SELECT_MODE: "SELECT_MODE",
    PLAY_MEDIA: "PLAY_MEDIA",
    STOP_MEDIA: "STOP_MEDIA",
    REQUEST_LYRIC: "REQUEST_LYRIC",
    RECEIVE_LYRIC: "RECEIVE_LYRIC",
    SEARCH_ONLINE_MEDIA: "SEARCH_ONLINE_MEDIA",
    SEARCH_LOCAL_MEDIA: "SEARCH_LOCAL_MEDIA",
    ERROR_REPORT: "ERROR_REPORT",
    SETTINGS: "SETTINGS"
}

export default constant
