const constant = {
    SELECT_MENU: "SELECT_MENU",
    REQUEST_LYRIC: "REQUEST_LYRIC",
    RECEIVE_LYRIC: "RECEIVE_LYRIC",
    SEARCH_ONLINE_MUSIC: "SEARCH_ONLINE_MUSIC",
    SEARCH_LOCAL_MUSIC: "SEARCH_LOCAL_MUSIC",
    ERROR_REPORT: "ERROR_REPORT",
    SETTINGS: "SETTINGS"
}

export default constant
