const constant = {
    SELECT_VIEW: "SELECT_VIEW",
    SELECT_MODE: "SELECT_MODE",
    PLAY_SONG: "PLAY_SONG",
    STOP_SONG: "STOP_SONG",
    REQUEST_LYRIC: "REQUEST_LYRIC",
    RECEIVE_LYRIC: "RECEIVE_LYRIC",
    SEARCH_ONLINE_MUSIC: "SEARCH_ONLINE_MUSIC",
    SEARCH_LOCAL_MUSIC: "SEARCH_LOCAL_MUSIC",
    ERROR_REPORT: "ERROR_REPORT",
    SETTINGS: "SETTINGS"
}

export default constant
