const constant = {
    SELECT_VIEW: "SELECT_VIEW",
    SELECT_SETTINGS_TAB: "SELECT_SETTINGS_TAB",
    SELECT_MODE: "SELECT_MODE",
    MEDIA_MODE: "MEDIA_MODE",
    PLAY_MEDIA: "PLAY_MEDIA",
    STOP_MEDIA: "STOP_MEDIA",
    REQUEST_LYRIC: "REQUEST_LYRIC",
    RECEIVE_LYRIC: "RECEIVE_LYRIC",
    ERROR_REPORT: "ERROR_REPORT",
    UPDATE_LIBRARY: "UPDATE_LIBRARY",
    UPDATE_FAVOURITE: "UPDATE_FAVOURITE",
    UPDATE_PLAYIST: "UPDATE_PLAYIST",
    SHOULD_UPDATE: "SHOULD_UPDATE",
    REQUEST_UPDATE: "REQUEST_UPDATE",
    REMOVE_MEDIA: "REMOVE_MEDIA",
    VISIBLE_COLUMN: "VISIBLE_COLUMN",
    UPDATE_MEDIA_INFO: "UPDATE_MEDIA_INFO",
    DOWNLOAD_AND_STREAM: "DOWNLOAD_AND_STREAM"
}

export default constant
