const constant = {
    SELECT_VIEW: "SELECT_VIEW",
    SELECT_SETTINGS_TAB: "SELECT_SETTINGS_TAB",
    SELECT_MODE: "SELECT_MODE",
    MEDIA_MODE: "MEDIA_MODE",
    PLAY_MEDIA: "PLAY_MEDIA",
    STOP_MEDIA: "STOP_MEDIA",
    REQUEST_LYRIC: "REQUEST_LYRIC",
    RECEIVE_LYRIC: "RECEIVE_LYRIC",
    SEARCH_ONLINE_MEDIA: "SEARCH_ONLINE_MEDIA",
    SEARCH_LOCAL_MEDIA: "SEARCH_LOCAL_MEDIA",
    ERROR_REPORT: "ERROR_REPORT",
    UPDATE_LIBRARY: "UPDATE_LIBRARY",
    UPDATE_FAVOURITE: "UPDATE_FAVOURITE",
    UPDATE_PLAYIST: "UPDATE_PLAYIST",
    SHOULD_UPDATE: "SHOULD_UPDATE",
    REQUEST_UPDATE: "REQUEST_UPDATE"
}

export default constant
